### ISSUE TITLE
_react.default.memo is not a function

### ISSUE THREAD

**Issue by Luchanso** [CompuIves/codesandbox-client#1426]
# 🐛 bug report

## Description of the problem
Hi, React API have function [React.memo](https://reactjs.org/docs/react-api.html#reactmemo), but when I try to use it, I fail 😞

Example:
```jsx
// TypeError _react.default.memo is not a function
const Test = React.memo(() => <div />);
```

###  Link to sandbox: [link](https://codesandbox.io/s/jjxz7j8m7y)

**Comment by lbogdan** [comment]
Hey @Luchanso , [`React.memo()` has been added in 16.6.0](https://reactjs.org/blog/2018/10/23/react-v-16-6.html), and you're using 16.5.2 in the linked sandbox.

**Comment by Luchanso** [comment]
@lbogdan yeah, are you sure.

**Comment by babul101** [comment]
Yes it is working on 16.8.6 version
